name: GitHub build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']
    name: Node ${{ matrix.node }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
